config = {
    "start_heat" : 20,
    "start_cool" : 80,
    "led_heat" : 13,
    "led_cool" : 6,
    "led_power" : 5,
    "gate_led_open" : 26,
    "gate_led_closed": 19,
    "relay_heat" : 17,
    "relay_cool" : 27,
    "heat" : "Heat",
    "cool" : "Cool",
    "off" : "Off",
    "lcdmode" : "i2c",
    "cols" : 20,
    "rows" : 4,
    "charmap" : "A00",
    "i2c_expander" : "PCF8574",
    "address" : 0x27,
    "port" : 1,
    "loop_delay": 1,
    "lcd_switch" : 11,
    "lcd_state" : False,
    "sensor_gate": 23
}
