config = {
    "start_heat" : 20,
    "start_cool" : 80,
    "gpio_lcd_switch" : 11,
    "gpio_led_heat" : 13,
    "gpio_led_cool" : 6,
    "gpio_led_power" : 5,
    "gpio_led_closed": 19,
    "gpio_led_open" : 26,
    "gpio_relay_cool" : 27,
    "gpio_relay_heat" : 17,
    "gpio_sensor_gate": 23,
    "heat" : "Heat",
    "cool" : "Cool",
    "off" : "Off",
    "lcdmode" : "i2c",
    "cols" : 20,
    "rows" : 4,
    "charmap" : "A00",
    "i2c_expander" : "PCF8574",
    "address" : 0x27,
    "port" : 1,
    "loop_delay": 1,
    "lcd_state" : False,

    "vent_side_open": 30,
    "vent_side_closed": 106,
    "vent_front_open": 2,
    "vent_front_closed": 178
}
